# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rVjGfaPC-CsDz6VudqgvSmihUrFz2HkX

Write a python program to print marks of the students using series in pandas library
:
"""

import pandas as pd

student_marks = {
    'Rithik': 85,
    'Michael': 78,
    'Deepak': 92,
    'Harsha': 74,
    'Saleem Chintu': 88
}

marks_series = pd.Series(student_marks)

marks_series

import pandas as pd
import numpy as np

marks_array = np.array([85, 78, 92, 74, 88])

student_names = ['Rithik', 'Michael', 'Deepak', 'Harsha', 'Saleem Chintu']

marks_series = pd.Series(data=marks_array, index=student_names)

marks_series

